name: CI

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ugoprenat/ugoprenat
  DOCKER_CONTAINER: ugoprenat
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  HOST_PORT: 4004

jobs:
  update_docker_image:
    name: Update Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ugoprenat
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64

  connect_to_vps:
    name: Connect to VPS and run docker image
    needs: [update_docker_image]
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Connect to VPS and run docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            CONTAINER_ID=$(docker ps --quiet --filter "ancestor=${{ steps.meta.outputs.tags }}")
              if [ -n "$CONTAINER_ID" ]; then
                docker stop $CONTAINER_ID
              fi
            docker system prune -f
            docker pull ${{ steps.meta.outputs.tags }}
            docker run -d -p ${{ env.HOST_PORT }}:3000 --name ${{ env.DOCKER_CONTAINER }} ${{ steps.meta.outputs.tags }}
